import { MetricsResponse, Review } from "./types";

export const mockMetrics: MetricsResponse = {
    totalReviews: 1284,
    sentimentDistribution: {
        POSITIVE: 512,
        NEGATIVE: 298,
        NEUTRAL: 341,
        MIXED: 133,
    },
    averageScores: {
        Positive: 0.4215,
        Negative: 0.2187,
        Neutral: 0.2634,
        Mixed: 0.0964,
    },
    churnRiskDistribution: {
        HIGH: 187,
        MEDIUM: 342,
        LOW: 755,
    },
};

export const mockReviews: Review[] = [
    {
        reviewId: "R001",
        customerName: "Alice Johnson",
        reviewText:
            "Absolutely love this product! It has completely transformed my workflow and saved me hours every week.",
        date: "2025-11-01",
        sentiment: "POSITIVE",
        sentimentScores: { Positive: 0.97, Negative: 0.01, Neutral: 0.01, Mixed: 0.01 },
        keyPhrases: ["product", "workflow", "hours"],
        churnRisk: "LOW",
        negativeScore: 0.01,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-01T10:30:00Z",
    },
    {
        reviewId: "R002",
        customerName: "Bob Martinez",
        reviewText:
            "Terrible experience. The app crashed three times today and I lost all my data. Considering canceling my subscription.",
        date: "2025-11-02",
        sentiment: "NEGATIVE",
        sentimentScores: { Positive: 0.01, Negative: 0.94, Neutral: 0.03, Mixed: 0.02 },
        keyPhrases: ["app", "data", "subscription"],
        churnRisk: "HIGH",
        negativeScore: 0.94,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-02T10:30:00Z",
    },
    {
        reviewId: "R003",
        customerName: "Carol Williams",
        reviewText:
            "It's okay, nothing special. Does what it says but the UI feels outdated compared to competitors.",
        date: "2025-11-03",
        sentiment: "NEUTRAL",
        sentimentScores: { Positive: 0.12, Negative: 0.18, Neutral: 0.62, Mixed: 0.08 },
        keyPhrases: ["UI", "competitors"],
        churnRisk: "LOW",
        negativeScore: 0.18,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-03T10:30:00Z",
    },
    {
        reviewId: "R004",
        customerName: "David Chen",
        reviewText:
            "Outstanding customer support! They resolved my issue within minutes. The product itself is solid.",
        date: "2025-11-04",
        sentiment: "POSITIVE",
        sentimentScores: { Positive: 0.92, Negative: 0.02, Neutral: 0.04, Mixed: 0.02 },
        keyPhrases: ["customer support", "issue", "product"],
        churnRisk: "LOW",
        negativeScore: 0.02,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-04T10:30:00Z",
    },
    {
        reviewId: "R005",
        customerName: "Emma Davis",
        reviewText:
            "Very disappointed. Features that were promised in the last update are still missing. Feels like false advertising.",
        date: "2025-11-05",
        sentiment: "NEGATIVE",
        sentimentScores: { Positive: 0.02, Negative: 0.88, Neutral: 0.06, Mixed: 0.04 },
        keyPhrases: ["features", "update", "false advertising"],
        churnRisk: "HIGH",
        negativeScore: 0.88,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-05T10:30:00Z",
    },
    {
        reviewId: "R006",
        customerName: "Frank Wilson",
        reviewText:
            "Great value for money. The free tier is generous and the paid plans are reasonable.",
        date: "2025-11-06",
        sentiment: "POSITIVE",
        sentimentScores: { Positive: 0.89, Negative: 0.03, Neutral: 0.06, Mixed: 0.02 },
        keyPhrases: ["value", "free tier", "paid plans"],
        churnRisk: "LOW",
        negativeScore: 0.03,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-06T10:30:00Z",
    },
    {
        reviewId: "R007",
        customerName: "Grace Lee",
        reviewText:
            "The onboarding process was confusing and I almost gave up. Once I figured it out, the product was decent.",
        date: "2025-11-08",
        sentiment: "MIXED",
        sentimentScores: { Positive: 0.25, Negative: 0.3, Neutral: 0.15, Mixed: 0.3 },
        keyPhrases: ["onboarding process", "product"],
        churnRisk: "MEDIUM",
        negativeScore: 0.3,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-08T10:30:00Z",
    },
    {
        reviewId: "R008",
        customerName: "Henry Taylor",
        reviewText:
            "Worst purchase I've ever made. Buggy, slow, and the support team is unresponsive. Want a refund immediately.",
        date: "2025-11-09",
        sentiment: "NEGATIVE",
        sentimentScores: { Positive: 0.0, Negative: 0.97, Neutral: 0.02, Mixed: 0.01 },
        keyPhrases: ["purchase", "support team", "refund"],
        churnRisk: "HIGH",
        negativeScore: 0.97,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-09T10:30:00Z",
    },
    {
        reviewId: "R009",
        customerName: "Isabelle Brown",
        reviewText:
            "Really impressed with the latest update. The new dashboard is clean and the analytics are powerful.",
        date: "2025-11-10",
        sentiment: "POSITIVE",
        sentimentScores: { Positive: 0.93, Negative: 0.01, Neutral: 0.04, Mixed: 0.02 },
        keyPhrases: ["update", "dashboard", "analytics"],
        churnRisk: "LOW",
        negativeScore: 0.01,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-10T10:30:00Z",
    },
    {
        reviewId: "R010",
        customerName: "James Anderson",
        reviewText:
            "Mixed feelings. Some features are excellent but the mobile app is barely functional.",
        date: "2025-11-11",
        sentiment: "MIXED",
        sentimentScores: { Positive: 0.28, Negative: 0.32, Neutral: 0.1, Mixed: 0.3 },
        keyPhrases: ["features", "mobile app"],
        churnRisk: "MEDIUM",
        negativeScore: 0.32,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-11T10:30:00Z",
    },
    {
        reviewId: "R011",
        customerName: "Karen Thomas",
        reviewText:
            "Been using this for 6 months and it keeps getting better. The team clearly listens to feedback.",
        date: "2025-11-12",
        sentiment: "POSITIVE",
        sentimentScores: { Positive: 0.91, Negative: 0.02, Neutral: 0.05, Mixed: 0.02 },
        keyPhrases: ["team", "feedback"],
        churnRisk: "LOW",
        negativeScore: 0.02,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-12T10:30:00Z",
    },
    {
        reviewId: "R012",
        customerName: "Liam Jackson",
        reviewText:
            "Charged me twice this month and still waiting for a refund after 2 weeks. Unacceptable.",
        date: "2025-11-13",
        sentiment: "NEGATIVE",
        sentimentScores: { Positive: 0.01, Negative: 0.92, Neutral: 0.04, Mixed: 0.03 },
        keyPhrases: ["refund", "charged"],
        churnRisk: "HIGH",
        negativeScore: 0.92,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-13T10:30:00Z",
    },
    {
        reviewId: "R013",
        customerName: "Mia White",
        reviewText:
            "The API documentation is excellent. Integration was seamless and took less than an hour.",
        date: "2025-11-14",
        sentiment: "POSITIVE",
        sentimentScores: { Positive: 0.94, Negative: 0.01, Neutral: 0.03, Mixed: 0.02 },
        keyPhrases: ["API documentation", "integration"],
        churnRisk: "LOW",
        negativeScore: 0.01,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-14T10:30:00Z",
    },
    {
        reviewId: "R014",
        customerName: "Noah Harris",
        reviewText:
            "Product is fine but way overpriced for what it offers. Competitors give more for less.",
        date: "2025-11-15",
        sentiment: "NEGATIVE",
        sentimentScores: { Positive: 0.08, Negative: 0.62, Neutral: 0.2, Mixed: 0.1 },
        keyPhrases: ["product", "competitors"],
        churnRisk: "HIGH",
        negativeScore: 0.62,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-15T10:30:00Z",
    },
    {
        reviewId: "R015",
        customerName: "Olivia Martin",
        reviewText:
            "This is exactly what our team needed. Collaboration features are top-notch and the real-time sync is flawless.",
        date: "2025-11-16",
        sentiment: "POSITIVE",
        sentimentScores: { Positive: 0.95, Negative: 0.01, Neutral: 0.03, Mixed: 0.01 },
        keyPhrases: ["team", "collaboration features", "real-time sync"],
        churnRisk: "LOW",
        negativeScore: 0.01,
        sourceFile: "uploads/batch_nov.csv",
        processedAt: "2025-11-16T10:30:00Z",
    },
];
